name: "resnet50_ensemble"
platform: "ensemble"
max_batch_size: 128
input [
  {
    name: "INPUT"
    data_type: TYPE_FP32
    dims: [ 224, 224, 3 ]
  }
]
output [
  {
    name: "OUTPUT"
    data_type: TYPE_FP32
    dims: [ 1000 ]
    label_filename: "resnet50_labels.txt"
  }
]
ensemble_scheduling {
  step [
    {
      model_name: "resnet50"
      model_version: -1
      input_map {
        key: "InputImage"
        value: "INPUT"
      }
      output_map {
        key: "resnet_v1_50/pool5"
        value: "preprocessed_image"
      }
    },
    {
      model_name: "resnet50_classifier"
      model_version: -1
      input_map {
        key: "Input"
        value: "preprocessed_image"
      }
      output_map {
        key: "resnet_v1_50/logits/Softmax"
        value: "OUTPUT"
      }
    }
  ]
}


