name: "ae"
platform: "tensorflow_graphdef"
max_batch_size: 100
input [
  {
    name: "dense_1_input"
    data_type: TYPE_FP32
    dims: [ 276 ]
  }
]
output [
  {
    name: "activation_12/Relu"
    data_type: TYPE_FP32
    dims: [ 276 ]
  }
]
instance_group [
  {
    kind: KIND_GPU,
    count: 1
  }
]
dynamic_batching {
  preferred_batch_size: [ 1 ]
  max_queue_delay_microseconds: 100
}

